version: '3.7'

services:
  my_website:
    image: altjohndev/my-website:${COMPOSE_IMAGE_TAG:-unstable}
    ports:
      - ${HOST_PORT:-80}:80
    networks:
      - network

networks:
  network:
    name: ${COMPOSE_NETWORK_NAME:-altjohndev}
