version: '3.7'

services:
  my_website:
    image: altjohndev/my-website:release
    build:
      context: app
      args:
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      dockerfile: ../${COMPOSE_DOCKERFILE_BUILD_TYPE:-scratch}.Dockerfile
